site_name: Koma
pages:
    - Home: index.md
    - Usage guide:
        - Functionality Overview: guide/functionality.md
        - Linear Algebra: guide/linalg.md
        - N-Dimensional Containers: guide/ndims.md
        - Plotting: guide/plotting.md
    - Advanced:
        - Build From Source: advanced/source.md
        - Contributing: advanced/contributing.md
theme: cosmo
